use food_business_db;

-- insert customer records with status approved and rejected

INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer1','customer1@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer2','customer2@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer3','customer3@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer4','customer4@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer5','customer5@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer6','customer6@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer7','customer7@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer8','customer8@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer9','customer9@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer10','customer10@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer11','customer11@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer12','customer12@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer13','customer13@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer14','customer14@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer15','customer15@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer16','customer16@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer17','customer17@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer18','customer18@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer19','customer19@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer20','customer20@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer21','customer21@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer22','customer22@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer23','customer23@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer24','customer24@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer25','customer25@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer26','customer26@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer27','customer27@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer28','customer28@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer29','customer29@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer30','customer30@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer31','customer31@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer32','customer32@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer33','customer33@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer34','customer34@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer35','customer35@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer36','customer36@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer37','customer37@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer38','customer38@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer39','customer39@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer40','customer40@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer41','customer41@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer42','customer42@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer43','customer43@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer44','customer44@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer45','customer45@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer46','customer46@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer47','customer47@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer48','customer48@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer49','customer49@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer50','customer50@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer51','customer51@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer52','customer52@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer53','customer53@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer54','customer54@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer55','customer55@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer56','customer56@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer57','customer57@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer58','customer58@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer59','customer59@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer60','customer60@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer61','customer61@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer62','customer62@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer63','customer63@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer64','customer64@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer65','customer65@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer66','customer66@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer67','customer67@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer68','customer68@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer69','customer69@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer70','customer70@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer71','customer71@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer72','customer72@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer73','customer73@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer74','customer74@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer75','customer75@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer76','customer76@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer77','customer77@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer78','customer78@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer79','customer79@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer80','customer80@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer81','customer81@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer82','customer82@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer83','customer83@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer84','customer84@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer85','customer85@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer86','customer86@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer87','customer87@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer88','customer88@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer89','customer89@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer90','customer90@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer91','customer91@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer92','customer92@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer93','customer93@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer94','customer94@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer95','customer95@example.com' , 1 ,'Rejected','Incomplete information','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer96','customer96@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer97','customer97@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer98','customer98@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer99','customer99@example.com' , 1 ,'Approved','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer100','customer100@example.com' , 1 ,'Pending','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);
INSERT INTO Customer (cust_name, Email, is_active,registration_status,reject_reason,password,mobile,gender,created_at) VALUES ('customer101','customer101@example.com' , 1 ,'Pending','','024ca8e38b33f9116c151123eb432d20', '+6534345345' , 'male' , CURRENT_TIMESTAMP);

Select * from Customer;

-- insert LoginActivity records with status approved and rejected

INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (2,'Mobile','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (2,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (6,'Mobile','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (5,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Mobile','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (5,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (9,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (5,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Website','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (5,'Website','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (9,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (6,'Mobile','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (5,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (2,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (6,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (2,'Mobile','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Website','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (6,'Mobile','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (2,'Website','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (9,'Mobile','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Website','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Mobile','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (6,'Website','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Mobile','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (4,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','MON', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (1,'Website','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (5,'Website','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (9,'Mobile','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','THU', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','WED', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Mobile','SUN', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (3,'Website','FRI', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (7,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','WED', CURRENT_TIMESTAMP);

INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (6,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (10,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (13,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Mobile','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (23,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (18,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (31,'Website','TUE', CURRENT_TIMESTAMP);
INSERT INTO LoginActivity (customer_id, login_channel, day_of_week , login_date) VALUES (8,'Mobile','TUE', CURRENT_TIMESTAMP);

Select * from LoginActivity;



-- insert devices

INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (1,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (2,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (3,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (4,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (5,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (6,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (7,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (8,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (9,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (10,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (11,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (12,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (13,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (14,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (15,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (16,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (17,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (18,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (19,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (20,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (21,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (22,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (23,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (24,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (25,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (26,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (27,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (28,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (29,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (30,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (31,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (32,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (33,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (34,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (35,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (36,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (37,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (38,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (39,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (40,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (41,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (42,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (43,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (44,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (45,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (46,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (47,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (48,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (49,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (50,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (51,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (52,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (53,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (54,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (55,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (56,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (57,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (58,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (59,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (60,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (61,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (62,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (63,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (64,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (65,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (66,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (67,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (68,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (69,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (70,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (71,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (72,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (73,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (74,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (75,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (76,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (77,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (78,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (79,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (80,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (81,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (82,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (83,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (84,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (85,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (86,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (87,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (88,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (89,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (90,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (91,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (92,'werertryrtyyfghffgkdjflsjgagjoarphkoptggdf+sdfdjngknkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','iOS','14');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (93,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (94,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (95,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (96,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (97,'','Desktop','15572.57.0');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (98,'dsfdkhfgepiruhgieubhncxmvnkvhroehroiqeujbnkfbnkbqobinoibnorjbiqhdbiqojrboirjeboklfdsldv+dvdfvvepvvt=','Android','13');
INSERT INTO DeviceDetails (customer_id, fcm_token , device_type, os_version) VALUES (99,'','Desktop','15572.57.0');

Select * from DeviceDetails;

-- insert data into the SellerDetails
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller1','seller1@example.com','Seller number 1 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller2','seller2@example.com','Seller number 2 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller3','seller3@example.com','Seller number 3 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller4','seller4@example.com','Seller number 4 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller5','seller5@example.com','Seller number 5 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller6','seller6@example.com','Seller number 6 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller7','seller7@example.com','Seller number 7 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller8','seller8@example.com','Seller number 8 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller9','seller9@example.com','Seller number 9 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller10','seller10@example.com','Seller number 10 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller11','seller11@example.com','Seller number 11 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller12','seller12@example.com','Seller number 12 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller13','seller13@example.com','Seller number 13 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller14','seller14@example.com','Seller number 14 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller15','seller15@example.com','Seller number 15 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller16','seller16@example.com','Seller number 16 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller17','seller17@example.com','Seller number 17 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller18','seller18@example.com','Seller number 18 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller19','seller19@example.com','Seller number 19 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller20','seller20@example.com','Seller number 20 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller21','seller21@example.com','Seller number 21 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller22','seller22@example.com','Seller number 22 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller23','seller23@example.com','Seller number 23 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller24','seller24@example.com','Seller number 24 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller25','seller25@example.com','Seller number 25 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller26','seller26@example.com','Seller number 26 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller27','seller27@example.com','Seller number 27 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller28','seller28@example.com','Seller number 28 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller29','seller29@example.com','Seller number 29 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller30','seller30@example.com','Seller number 30 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller31','seller31@example.com','Seller number 31 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller32','seller32@example.com','Seller number 32 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller33','seller33@example.com','Seller number 33 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller34','seller34@example.com','Seller number 34 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller35','seller35@example.com','Seller number 35 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller36','seller36@example.com','Seller number 36 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller37','seller37@example.com','Seller number 37 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller38','seller38@example.com','Seller number 38 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller39','seller39@example.com','Seller number 39 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller40','seller40@example.com','Seller number 40 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller41','seller41@example.com','Seller number 41 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller42','seller42@example.com','Seller number 42 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller43','seller43@example.com','Seller number 43 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller44','seller44@example.com','Seller number 44 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller45','seller45@example.com','Seller number 45 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller46','seller46@example.com','Seller number 46 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller47','seller47@example.com','Seller number 47 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller48','seller48@example.com','Seller number 48 ,Singapore', CURRENT_TIMESTAMP);
INSERT INTO SellerDetails (seller_name, seller_email, seller_address, created_date) VALUES ('Seller49','seller49@example.com','Seller number 49 ,Singapore', CURRENT_TIMESTAMP);

Select * from SellerDetails;
-- FoodListing inserting records

INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food1',73.14,29,1);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food2',61.91,33,2);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food3',34.63,54,3);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food4',66.74,11,4);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food5',25.04,53,5);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food6',53.17,55,6);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food7',31.33,33,7);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food8',43.1,37,8);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food9',14.97,14,9);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food10',27.83,39,10);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food11',16.16,50,11);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food12',69.95,34,12);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food13',63.02,11,13);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food14',22.95,67,14);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food15',40.26,13,15);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food16',61.8,31,16);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food17',12.3,8,17);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food18',36.73,35,18);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food19',57.28,19,19);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food20',69.23,17,20);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food21',29.52,29,21);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food22',34.37,47,22);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food23',37.86,19,23);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food24',54.12,26,24);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food25',35.01,45,25);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food26',47.29,23,26);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food27',50.13,70,27);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food28',21.6,29,28);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food29',61.51,56,29);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food30',74.43,13,30);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food31',70.78,7,31);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food32',18.98,40,32);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food33',30.83,15,33);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food34',51.43,56,34);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food35',30.55,44,35);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food36',55.03,51,36);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food37',58.53,26,37);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food38',47.79,64,38);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food39',15.48,50,39);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food40',44.93,19,40);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food41',33.56,59,41);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food42',12.17,22,42);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food43',43.33,36,43);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food44',37.59,47,44);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food433',37.43,47,44);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food45',17.6,69,45);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food46',23.23,19,46);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food47',74.76,16,47);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food48',36.86,22,48);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food49',62.24,70,49);
INSERT INTO FoodListing (food_name, selling_price, avbl_quantity, seller_id) VALUES ('Food50',72.24,70,49);

Select * from FoodListing;

-- Insert in pruchase table

INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (61,16,3,48.77 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (19,47,12,306.94 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (66,48,20,403.6 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (95,17,8,218.39 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (71,13,10,285.67 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (6,13,25,287.85 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (20,1,22,342.56 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,8,2,32.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (39,50,29,657.25 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (2,43,24,294.46 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (98,15,16,322.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (36,35,21,467.5 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (38,28,24,493.12 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (57,38,16,196.77 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (78,49,26,292.61 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (32,31,18,527.93 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (15,27,7,146.16 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (51,39,14,157.09 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (28,22,16,418.2 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (32,10,23,362.78 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (79,23,1,26.19 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (44,34,30,620.62 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (70,40,20,223.09 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (2,48,7,203.92 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (14,46,3,83.73 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (23,30,18,481.02 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (82,47,17,248.28 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (49,39,16,276.08 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (90,42,16,303.22 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (79,15,25,374.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (28,27,3,88.22 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (36,9,22,372.13 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (90,46,28,832.94 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (80,1,20,309.7 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (77,9,4,58.71 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (42,25,10,161.92 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (32,20,20,273.15 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (8,31,18,356.03 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (86,5,25,513.41 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (82,29,6,149.26 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (44,44,16,469.03 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (25,18,2,35.18 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (81,21,12,275.41 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (73,41,17,439.65 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (31,21,8,198.7 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (35,24,29,751.45 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (61,41,3,89.65 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (9,44,3,78.09 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (66,48,11,298.63 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (41,39,7,204.76 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (94,16,1,15.59 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (31,8,17,273.4 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (67,37,23,655.04 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (22,24,26,640.37 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (26,42,11,201.99 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (9,15,8,131.84 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,41,9,248.8 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (79,41,19,555.8 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (94,36,12,135.76 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (97,48,9,175.51 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (93,10,17,467.46 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (75,36,19,208.7 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (19,16,20,421.74 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (25,12,23,544.65 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (24,12,8,216.91 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (96,36,9,236.23 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (4,28,28,318.24 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (87,35,11,117.7 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (35,10,30,792.14 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (56,46,11,237.32 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (33,31,16,321.64 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (55,31,18,537.64 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (96,39,25,338.75 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (100,21,22,370.23 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (96,17,6,98.18 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (3,35,2,53.92 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (2,40,7,145.53 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (15,19,16,273.83 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (17,6,9,126.01 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (86,37,28,696.97 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (83,15,20,386.21 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (11,42,10,190.34 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (78,19,24,415.35 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (87,48,22,603.94 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (24,27,25,612.27 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (60,36,13,143.03 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (97,30,18,325.74 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (39,5,23,592.44 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (25,26,5,123.12 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (8,11,12,236.06 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (77,28,1,28.33 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (99,28,21,451.15 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (27,22,17,227.36 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (22,41,1,15.36 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (74,29,17,413.61 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (79,8,27,522.86 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (77,26,4,94.27 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (60,32,22,519.33 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (17,45,25,592.86 , CURRENT_TIMESTAMP);

INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (20,1,22,342.56 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,8,2,32.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (20,5,22,342.56 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,8,2,32.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (20,3,22,342.56 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,8,2,32.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (20,5,22,342.56 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,8,2,32.79 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (20,5,22,342.56 , CURRENT_TIMESTAMP);
INSERT INTO PurchaseTransactions (customer_id, item_id, purchase_qauntity, price , purchase_datetime) VALUES (76,12,2,32.79 , CURRENT_TIMESTAMP);

Select * from PurchaseTransactions;

