WITH login_activity_qty AS (
SELECT 
    day_of_week AS HIGHEST_NUMBER_OF_LOGIN_DAY,
    COUNT(*) AS TOTAL_QUANTITY,
	DENSE_RANK() OVER (ORDER BY COUNT(*)  DESC) AS Ranking
FROM
    LoginActivity 
    GROUP BY HIGHEST_NUMBER_OF_LOGIN_DAY  ORDER By TOTAL_QUANTITY DESC
) SELECT HIGHEST_NUMBER_OF_LOGIN_DAY,TOTAL_QUANTITY
FROM login_activity_qty where Ranking=1;